language: csharp
solution: ./Travis.Tests/Travis.Tests.sln
install:
  - nuget restore ./Travis.Tests/Travis.Tests.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./Travis.Tests/Travis.Tests.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Travis.NUnitTests/bin/Release/Travis.NUnitTests.dll
