language: csharp
solution: ./Travis.Tests/Travis.Tests.sln
install:
  - nuget restore ./Travis.Tests/Travis.Tests.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./Travis.Tests/Travis.Tests.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Travis.NUnitTests/bin/Release/Travis.NUnitTests.dll
